# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.project_member import ProjectMember  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectMember(unittest.TestCase):
    """ProjectMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectMember(self):
        """Test ProjectMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.project_member.ProjectMember()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
