# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tags import Tags  # noqa: E501
from swagger_client.rest import ApiException


class TestTags(unittest.TestCase):
    """Tags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTags(self):
        """Test Tags"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tags.Tags()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
