# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.  # noqa: E501

    OpenAPI spec version: 1.6.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.manifest import Manifest  # noqa: E501
from swagger_client.rest import ApiException


class TestManifest(unittest.TestCase):
    """Manifest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManifest(self):
        """Test Manifest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.manifest.Manifest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
